plugin_name = 'EXAMPLE_splitter'

def options(opt):
  pass

def configure(conf):
  pass

def build(bld):
  bld.shlib(
    source = plugin_name + '.cpp',
    target = plugin_name,
    use='JUBACONVERTER',
    )

  bld.program(
    source = 'client.cpp',
    target = 'client',
    use='PFICOMMON MSGPACK',
    )

  bld(
    rule = 'cp ${SRC} ${TGT}',
    source = 'converter_config.json',
    target = bld.path.get_bld(),
    )

  bld(
    rule = 'cp ${SRC} ${TGT}',
    source = 'jubaconv_example.sh',
    target = bld.path.get_bld(),
    )
